"""Probe `/api/avail-geo[/cells]` across a matrix of (bbox, window, budgets)
and emit a markdown reference table of (tier, res, cells, rows, bytes, ms).

Useful as:
  - documentation of what the system delivers at each viewport scale,
  - a manual regression check (compare numbers across runs),
  - a budgeting tool (catch responses that balloon at certain combos).

Usage:
    ctbk avail-geo-probe                    # default API base, markdown to stdout
    ctbk avail-geo-probe -b http://localhost:8787  # local dev
    ctbk avail-geo-probe -o specs/avail-geo-probe.md
"""
from __future__ import annotations

import json
import sys
import time
import urllib.request
from dataclasses import dataclass

from click import option

from ctbk.cli.base import ctbk

DEFAULT_API = 'https://ctbk-gbfs-api.ryan-0dc.workers.dev'

# Canonical bounding boxes — corner formula: (minLat, minLng, maxLat, maxLng)
BBOXES = {
    # ~50 km² — full NYC + JC + close Westchester. Cells at res 5 dominate.
    'nyc-region':       (40.55, -74.20, 40.95, -73.70),
    # ~25 km² — Manhattan + LIC + Bx + close Brooklyn.
    'core-nyc':         (40.68, -74.05, 40.85, -73.85),
    # ~5 km² — lower-to-mid Manhattan only.
    'manhattan-narrow': (40.74, -74.00, 40.78, -73.96),
    # ~0.5 km² — financial district / a handful of stations.
    'tip-of-manhattan': (40.71, -74.02, 40.72, -74.00),
}

# Canonical time windows.
WINDOWS = {
    'h1-1day':   ('2026-05-22T00:00:00Z', '2026-05-23T00:00:00Z', 24),
    'h1-7day':   ('2026-05-17T00:00:00Z', '2026-05-24T00:00:00Z', 168),  # multi-shard h1 stitch
    'd1-1month': ('2026-04-01T00:00:00Z', '2026-05-01T00:00:00Z', 30),
}

# (endpoint, default cell_budget)
ENDPOINTS = [
    ('/api/avail-geo',       200),   # rollup
    ('/api/avail-geo/cells', 200),   # per-cell
]


@dataclass
class ProbeResult:
    endpoint: str
    bbox_name: str
    window_name: str
    tier: str
    res: int
    cells_planned: int
    records: int
    bytes: int
    ms: float
    error: str | None = None


def probe(api_base: str, endpoint: str, bbox_name: str, window_name: str, cell_budget: int) -> ProbeResult:
    bbox = BBOXES[bbox_name]
    from_iso, to_iso, bin_budget = WINDOWS[window_name]
    bbox_str = ','.join(str(x) for x in bbox)
    url = (
        f'{api_base}{endpoint}'
        f'?from={from_iso}&to={to_iso}&bbox={bbox_str}'
        f'&bin_budget={bin_budget}&cell_budget={cell_budget}'
    )
    t0 = time.perf_counter()
    try:
        # CF rejects `Python-urllib/*` UA at the edge. A generic UA passes.
        req = urllib.request.Request(url, headers={'User-Agent': 'ctbk-avail-geo-probe/0.1'})
        with urllib.request.urlopen(req) as r:
            body = r.read()
        ms = (time.perf_counter() - t0) * 1000
        d = json.loads(body)
        if 'error' in d:
            return ProbeResult(endpoint, bbox_name, window_name, '', 0, 0, 0, len(body), ms, error=d['error'])
        plan = d.get('plan', {})
        return ProbeResult(
            endpoint=endpoint,
            bbox_name=bbox_name,
            window_name=window_name,
            tier=plan.get('outputTier', ''),
            res=plan.get('outputRes', 0),
            cells_planned=len(plan.get('outputCells', [])),
            records=len(d.get('records', [])),
            bytes=len(body),
            ms=ms,
        )
    except Exception as e:
        ms = (time.perf_counter() - t0) * 1000
        return ProbeResult(endpoint, bbox_name, window_name, '', 0, 0, 0, 0, ms, error=str(e))


def format_markdown(results: list[ProbeResult]) -> str:
    out: list[str] = []
    out.append('# avail-geo probe — reference response shapes\n')
    out.append('Generated by `ctbk avail-geo-probe`. Re-run to refresh after\n'
               'pipeline changes; commit deliberate shifts. See\n'
               '`specs/avail-geo-pyramid.md` for the underlying design.\n')
    for ep, _ in ENDPOINTS:
        ep_results = [r for r in results if r.endpoint == ep]
        out.append(f'\n## `{ep}`\n')
        out.append('| bbox | window | tier | res | cells planned | records | bytes | ms |')
        out.append('|------|--------|------|----:|---:|---:|---:|---:|')
        for r in ep_results:
            if r.error:
                out.append(f'| `{r.bbox_name}` | `{r.window_name}` | — | — | — | — | — | `error: {r.error[:60]}` |')
            else:
                out.append(
                    f'| `{r.bbox_name}` | `{r.window_name}` | `{r.tier}` | {r.res} | '
                    f'{r.cells_planned} | {r.records:,} | {r.bytes:,} | {r.ms:.0f} |'
                )
    out.append('\n## Bboxes\n')
    out.append('| name | min lat / lng → max lat / lng |')
    out.append('|------|------|')
    for name, (a, b, c, d) in BBOXES.items():
        out.append(f'| `{name}` | {a}, {b} → {c}, {d} |')
    out.append('\n## Windows\n')
    out.append('| name | from | to | bin_budget |')
    out.append('|------|------|----|-----------:|')
    for name, (f, t, b) in WINDOWS.items():
        out.append(f'| `{name}` | `{f}` | `{t}` | {b} |')
    return '\n'.join(out) + '\n'


@ctbk.command('avail-geo-probe', help="Probe avail-geo endpoints, emit markdown reference table.")
@option('-b', '--api-base', default=DEFAULT_API, help=f"API base URL (default: {DEFAULT_API})")
@option('-o', '--output', help="Output markdown file (default: stdout)")
@option('-c', '--cell-budget', type=int, default=200, help="cell_budget query param (default: 200)")
def avail_geo_probe(api_base: str, output: str | None, cell_budget: int):
    """Hit each (endpoint × bbox × window) combo, collect plan + payload size."""
    results: list[ProbeResult] = []
    for ep, _default_cb in ENDPOINTS:
        for window_name in WINDOWS:
            for bbox_name in BBOXES:
                print(f'  {ep} {bbox_name} {window_name}...', file=sys.stderr, flush=True)
                results.append(probe(api_base, ep, bbox_name, window_name, cell_budget))
    md = format_markdown(results)
    if output:
        with open(output, 'w') as f:
            f.write(md)
        print(f'wrote {output}', file=sys.stderr)
    else:
        print(md)
