name = "ctbk-gbfs-api"
main = "src/index.ts"
compatibility_date = "2024-09-23"

[[d1_databases]]
binding = "DB"
database_name = "ctbk-gbfs"
database_id = "d5746734-70ba-46aa-8780-be09e4837f0b"

# Permissive CORS for browser fetch from ctbk.dev
[vars]
CORS_ORIGIN = "*"
