name: CI
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 17 3-11 * *"
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-1
  GIT_BRANCH: ${{ github.event.pull_request && github.head_ref || github.ref_name }}
  MAIL_FROM: ${{ secrets.MAIL_USERNAME }}
  MAIL_PSWD: ${{ secrets.MAIL_PASSWORD }}
jobs:
  csvs:
    name: Unzip+Cache CSVs
    runs-on: ubuntu-latest
    steps:
      - uses: neighbor-ryan/ctbk.dev/.github/workflows/step.yml@main
      - run: python ctbk/csvs.py --s3
  normalized:
    name: Join regions, convert to Parquet
    runs-on: ubuntu-latest
    needs: csvs
    steps:
      - uses: neighbor-ryan/ctbk.dev/.github/workflows/step.yml@main
      - run: python ctbk/normalized.py --s3
  meta_hist:
    name: Compute station name / latlng histograms
    runs-on: ubuntu-latest
    needs: normalized
    steps:
      - uses: neighbor-ryan/ctbk.dev/.github/workflows/step.yml@main
      - run: python ctbk/stations/meta_hist.py --s3
  modes:
    name: Compute canonical station names, latlngs
    runs-on: ubuntu-latest
    needs: meta_hist
    steps:
      - uses: neighbor-ryan/ctbk.dev/.github/workflows/step.yml@main
      - run: python ctbk/stations/modes.py --s3 --json
  group_counts-start:
    name: Aggregate counts by start station
    runs-on: ubuntu-latest
    needs: normalized
    steps:
      - uses: neighbor-ryan/ctbk.dev/.github/workflows/step.yml@main
      - run: python ctbk/group_counts.py --s3 -s -c
  group_counts-start-end:
    name: Aggregate counts by station-pair
    runs-on: ubuntu-latest
    needs: normalized
    steps:
      - uses: neighbor-ryan/ctbk.dev/.github/workflows/step.yml@main
      - run: python ctbk/group_counts.py --s3 -se -c
  stations-db-start-end:
    name: Build stations DB (station-pair)
    runs-on: ubuntu-latest
    needs: modes
    steps:
      - uses: neighbor-ryan/ctbk.dev/.github/workflows/step.yml@main
      - run: python ctbk/stations/db.py --s3 -se -c
  group_counts-year-month-start-end:
    name: Aggregate counts by (month, station-pair)
    runs-on: ubuntu-latest
    needs: normalized
    steps:
      - uses: neighbor-ryan/ctbk.dev/.github/workflows/step.yml@main
      - run: python ctbk/group_counts.py --s3 -ymse -c
  stations-db-year-month-start-end:
    name: Build stations DB (month, station-pair)
    runs-on: ubuntu-latest
    needs: modes
    steps:
      - uses: neighbor-ryan/ctbk.dev/.github/workflows/step.yml@main
      - run: python ctbk/stations/db.py --s3 -ymse -c
  group_counts-year-month-region-gender-type-bike-counts-durations:
    name: Aggregate counts by (month, region, gender, user type, rideable type)
    runs-on: ubuntu-latest
    needs: normalized
    steps:
      - uses: neighbor-ryan/ctbk.dev/.github/workflows/step.yml@main
      - run: python ctbk/group_counts.py --s3 -ymrgtb -cd --email ${{ secrets.MAIL_TO }}
