name: CI
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 17 3-11 * *"
jobs:
  csvs:
    uses: neighbor-ryan/ctbk.dev/.github/workflows/step.yml@main
    with:
      name: Unzip+Cache CSVs
      run: python ctbk/csvs.py --s3
    secrets: inherit
  normalized:
    needs: csvs
    uses: neighbor-ryan/ctbk.dev/.github/workflows/step.yml@main
    with:
      name: Join regions, convert to Parquet
      run: python ctbk/normalized.py --s3
    secrets: inherit
  meta_hist:
    needs: normalized
    uses: neighbor-ryan/ctbk.dev/.github/workflows/step.yml@main
    with:
      name: Compute station name / latlng histograms
      run: python ctbk/stations/meta_hist.py --s3
    secrets: inherit
  modes:
    needs: meta_hist
    uses: neighbor-ryan/ctbk.dev/.github/workflows/step.yml@main
    with:
      name: Compute canonical station names, latlngs
      run: python ctbk/stations/modes.py --s3 --json
    secrets: inherit
  group_counts-start:
    needs: normalized
    uses: neighbor-ryan/ctbk.dev/.github/workflows/step.yml@main
    with:
      name: Aggregate counts by start station
      run: python ctbk/group_counts.py --s3 -s -c
    secrets: inherit
  group_counts-start-end:
    needs: normalized
    uses: neighbor-ryan/ctbk.dev/.github/workflows/step.yml@main
    with:
      name: Aggregate counts by station-pair
      run: python ctbk/group_counts.py --s3 -se -c
    secrets: inherit
  station_pair_jsons:
    needs: group_counts-start-end
    uses: neighbor-ryan/ctbk.dev/.github/workflows/step.yml@main
    with:
      name: Build stations DB (station-pair)
      run: python ctbk/station_pair_jsons.py --s3
    secrets: inherit
  group_counts-year-month-start-end:
    needs: normalized
    uses: neighbor-ryan/ctbk.dev/.github/workflows/step.yml@main
    with:
      name: Aggregate counts by (month, station-pair)
      run: python ctbk/group_counts.py --s3 -ymse -c
    secrets: inherit
  group_counts-year-month-region-gender-type-bike-counts-durations:
    needs: normalized
    uses: neighbor-ryan/ctbk.dev/.github/workflows/step.yml@main
    with:
      name: Aggregate counts by (month, region, gender, user type, rideable type)
      run: python ctbk/group_counts.py --s3 -ymrgtb -cd --do-email
    secrets: inherit
