name: CI
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 17 3-11 * *"
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-1
  GIT_BRANCH: ${{ github.event.pull_request && github.head_ref || github.ref_name }}
  MAIL_FROM: ${{ secrets.MAIL_USERNAME }}
  MAIL_PSWD: ${{ secrets.MAIL_PASSWORD }}
jobs:
  csvs:
    uses: neighbor-ryan/ctbk.dev/.github/workflows/step.yml@main
    with:
      name: Unzip+Cache CSVs
      run: python ctbk/csvs.py --s3
  normalized:
    needs: csvs
    uses: neighbor-ryan/ctbk.dev/.github/workflows/step.yml@main
    with:
      name: Join regions, convert to Parquet
      run: python ctbk/normalized.py --s3
  meta_hist:
    needs: normalized
    uses: neighbor-ryan/ctbk.dev/.github/workflows/step.yml@main
    with:
      name: Compute station name / latlng histograms
      run: python ctbk/stations/meta_hist.py --s3
  modes:
    needs: meta_hist
    uses: neighbor-ryan/ctbk.dev/.github/workflows/step.yml@main
    with:
      name: Compute canonical station names, latlngs
      run: python ctbk/stations/modes.py --s3 --json
  group_counts-start:
    needs: normalized
    uses: neighbor-ryan/ctbk.dev/.github/workflows/step.yml@main
    with:
      name: Aggregate counts by start station
      run: python ctbk/group_counts.py --s3 -s -c
  group_counts-start-end:
    needs: normalized
    uses: neighbor-ryan/ctbk.dev/.github/workflows/step.yml@main
    with:
      name: Aggregate counts by station-pair
      run: python ctbk/group_counts.py --s3 -se -c
  stations-db-start-end:
    needs: modes
    uses: neighbor-ryan/ctbk.dev/.github/workflows/step.yml@main
    with:
      name: Build stations DB (station-pair)
      run: python ctbk/stations/db.py --s3 -se -c
  group_counts-year-month-start-end:
    needs: normalized
    uses: neighbor-ryan/ctbk.dev/.github/workflows/step.yml@main
    with:
      name: Aggregate counts by (month, station-pair)
      run: python ctbk/group_counts.py --s3 -ymse -c
  stations-db-year-month-start-end:
    needs: modes
    uses: neighbor-ryan/ctbk.dev/.github/workflows/step.yml@main
    with:
      name: Build stations DB (month, station-pair)
      run: python ctbk/stations/db.py --s3 -ymse -c
  group_counts-year-month-region-gender-type-bike-counts-durations:
    needs: normalized
    uses: neighbor-ryan/ctbk.dev/.github/workflows/step.yml@main
    with:
      name: Aggregate counts by (month, region, gender, user type, rideable type)
      run: python ctbk/group_counts.py --s3 -ymrgtb -cd --email ${{ secrets.MAIL_TO }}
