name: CI
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 17 3-11 * *"
jobs:
  csvs:
    uses: ./.github/workflows/step.yml@main
    with:
      name: Unzip+Cache CSVs
      run: ctbk --s3 csvs create --dask
    secrets: inherit
  normalized:
    needs: csvs
    uses: ./.github/workflows/step.yml@main
    with:
      name: Join regions, convert to Parquet
      run: ctbk --s3 normalized create --dask
    secrets: inherit
  meta_hist-names:
    needs: normalized
    uses: ./.github/workflows/step.yml@main
    with:
      name: Compute station name histograms
      run: ctbk --s3 station-meta-hists create --dask -in
    secrets: inherit
  meta_hist-latlngs:
    needs: normalized
    uses: ./.github/workflows/step.yml@main
    with:
      name: Compute station lat/lng histograms
      run: ctbk --s3 station-meta-hists create --dask -il
    secrets: inherit
  group_counts-start:
    needs: normalized
    uses: ./.github/workflows/step.yml@main
    with:
      name: Aggregate counts by start station
      run: ctbk --s3 aggregated create --dask -s -c
    secrets: inherit
  group_counts-start-end:
    needs: normalized
    uses: ./.github/workflows/step.yml@main
    with:
      name: Aggregate counts by station-pair
      run: ctbk --s3 aggregated create --dask -se -c
    secrets: inherit
  group_counts-year-month-region-gender-type-bike-counts-durations:
    needs: normalized
    uses: ./.github/workflows/step.yml@main
    with:
      name: Aggregate counts by (month, region, gender, user type, rideable type)
      run: ctbk --s3 aggregated create --dask -ymrgtb -cd --do-email
    secrets: inherit
  modes:
    needs: [meta_hist-names, meta_hist-latlngs, group_counts-start]
    uses: ./.github/workflows/step.yml@main
    with:
      name: Compute canonical station names, latlngs
      run: ctbk --s3 station-modes create --dask
    secrets: inherit
  station_pair_jsons:
    needs: [modes, group_counts-start-end]
    uses: ./.github/workflows/step.yml@main
    with:
      name: Build station-pair count JSONs
      run: ctbk --s3 station-pair-jsons create --dask
    secrets: inherit
