name: CI
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 17 3-9 * *"
jobs:
  daily:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
        cache: pip
    - name: Set env/secret vars
      run: |
        echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
        echo "AWS_DEFAULT_REGION=us-east-1" >> $GITHUB_ENV
        echo "GIT_BRANCH=${{ github.event.pull_request && github.head_ref || github.ref_name }}" >> $GITHUB_ENV
        echo "MAIL_FROM=${{ secrets.MAIL_USERNAME }}" >> $GITHUB_ENV
        echo "MAIL_PSWD=${{ secrets.MAIL_PASSWORD }}" >> $GITHUB_ENV
    - name: Install Python dependencies
      run: pip install -e .
    - name: Unzip+Cache CSVs
      run: python ctbk/csvs.py --s3
    - name: Join regions, convert to Parquet
      run: python ctbk/normalized.py --s3
    - name: Compute station name / latlng histograms
      run: python ctbk/stations/meta_hist.py --s3
    - name: Compute station name / latlng histograms
      run: python ctbk/stations/modes.py --s3
    - name: Aggregate counts by (month, station-pair)
      run: python ctbk/group_counts.py --s3 -seGBTD
    - name: Aggregate counts by (month, region, gender, user type, rideable type)
      run: python ctbk/group_counts.py --s3 --email ${{ secrets.MAIL_TO }}
