name: S3 (s3://ctbk.dev)
on:
  push:
    branches:
      - dev
jobs:
  build:
    name: Build + Sync dev branch to s3://ctbk.dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: www/package-lock.json
      - name: Install
        run: |
          cd www
          npm install
      - name: Build
        run: |
          cd www
          npm run export
      - name: Sync
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.s3_ctbk_dev_access_key }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.s3_ctbk_dev_secret_key }}
          AWS_DEFAULT_REGION: us-east-1
        run: |
          aws s3 sync www/out/ s3://ctbkdev/
