name: GitHub Pages
on:
  push:
    branches:
      - www
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: www/package-lock.json
      - name: Install
        run: |
          cd www
          npm install
      - name: Build
        run: |
          cd www
          npm run export
          touch out/.nojekyll
      - name: Deploy to GH Page
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: ghp
          folder: www/out
