name: GitHub Pages
on:
  push:
    branches:
      - www
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Install
        run: |
          cd static
          npm install
      - name: Build
        run: |
          cd static
          npm run build
          mkdir -p built/assets
          cp -r index.html favicon.ico dist assets built/
      - name: Deploy to GH Page
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: ghp
          folder: static/built
