name: Run step
on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      run:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      MAIL_USERNAME:
        required: true
      MAIL_PASSWORD:
        required: true
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-1
  MAIL_FROM: ${{ secrets.MAIL_USERNAME }}
  MAIL_PSWD: ${{ secrets.MAIL_PASSWORD }}
jobs:
  run:
    name: ${{ inputs.name }}
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3
      - name: Setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: pip
      - name: Install pip deps
        run: pip install -e .
      - name: Echo cmd
        run: echo ${{ inputs.run }}
      - name: ${{ inputs.name }}
        run: ${{ inputs.run }}
