name: Run step
on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      run:
        required: true
        type: string
jobs:
  run:
    name: ${{ inputs.name }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: pip
      - name: Install pip deps
        run: pip install -e .
      - name: ${{ inputs.name }}
        run: ${{ inputs.run }}
