name: Setup env
on:
  workflow_call:
jobs:
  setup:
    name: Setup env
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
          cache: pip
      - run: pip install -e .
