name: Env var test
on:
  push:
    branches:
      - test
env:
  MAIL_TO: ${{ secrets.MAIL_TO }}
jobs:
  build_mailto_output:
    runs-on: ubuntu-latest
    outputs:
      run: "python ctbk/group_counts.py --s3 -ymrgtb -cd --email ${{ env.MAIL_TO }}"
    steps:
      - run: echo "Exposing env var"
  group_counts-year-month-region-gender-type-bike-counts-durations:
    needs: build_mailto_output
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "cmd: ${{ needs.build_mailto_output.outputs.run }}"
