name: Env var test
on:
  push:
    branches:
      - test
env:
  MAIL_TO: ${{ secrets.MAIL_TO }}
  testvar: yay
jobs:
  compute_var:
    runs-on: ubuntu-latest
    outputs:
      my_var: python
      mailto: ${{ env.MAIL_TO }}
      tv: ${{ env.testvar }}
      cmd: ${{ steps.echo.outputs.cmd }}
    steps:
      - id: echo
        run: |
          echo "Exposing output $my_var"
          echo "cmd=python ${{ env.MAIL_TO }} ${{ env.testvar }}" >> $GITHUB_OUTPUT
  use_var:
    needs: compute_var
    runs-on: ubuntu-latest
    env:
      computed_var: ${{ needs.compute_var.outputs.my_var }}
      step_envar: $testvar
    steps:
      - run: |
          echo cmd ${{ needs.compute_var.outputs.cmd }}
          echo "cmd ${{ needs.compute_var.outputs.cmd }}"
          echo my_var ${{ needs.compute_var.outputs.my_var }}
          echo computed_var $computed_var
          echo testvar $testvar, ${{ env.testvar }}
          echo step_envar $step_envar, ${{ env.step_envar }}
          echo mailto ${{ needs.compute_var.outputs.mailto }}
          echo MAIL_TO ${{ env.MAIL_TO }}, ${{ secrets.MAIL_TO }}
