name: Env var test
on:
  push:
    branches:
      - test
jobs:
  run_step:
    uses: neighbor-ryan/ctbk.dev/.github/workflows/test-reusable.yml@test
    with:
      name: Test step
      run: python test.py
    secrets: inherit
